### ISSUE TITLE
feat: Required minimum patcher version annotation or JSON export

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVancedTeam/revanced-patcher#223] opened 2023-08-27 02:24 UTC
### Type

Functionality

### Issue

Too many people fail to update Manager, and then they wonder why it's throwing class not found exceptions during patching.

### Feature

Create a minimum patcher version annotation that is applied to patches (apply it to some core patch such as integrations patch).

Or alternatively export something in the patches.json that indicates the minimum patcher version that is required to use the patches.

Then when a breaking patcher change is introduced, update the patches required minimum patcher field.

Then if Manager/CLI tries to patch and it's below the minimum patcher version, throw an error explaining to update.

### Motivation

Help users who get so lost when they neglect updating Manager.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment] 2023-08-27 17:53
I think this can be achieved without the help of ReVanced Patcher. The build system can add the version of ReVanced Patcher used to compile patches into the jar file as a resource.

**Comment by oSumAtrIX** [comment] 2024-02-11 20:34
This was previously an issue with breaking API changes. Currently, we handle this with more care and deprecation which will mitigate the issue in combination with ReVanced Manager showing a popup if an update is present. This could be enough to close the issue.

**Closed as not planned** 2024-12-05 17:46 UTC
Labels: Feature request

**Comment by oSumAtrIX** [comment] 2024-12-05 17:51
The issue is related to the API changing and old versions of manager stopping to display an update prompt. Fixing that would've weeded out this problem in particular.
